version: '3'

services:
  sentiment-api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DEBUG=False
    volumes:
      - ./app/model/data:/app/app/model/data
    restart: unless-stopped
